#!/system/bin/sh
#
# Print startup info
#
L="log -p i -t vegabean"

$L "Welcome to Android `getprop ro.build.version.release` / VegaBean";
$L "This is the banner for the systeminit rc1.d process";
$L "                                                _ ";
$L " __ __ _ ___  _ _  __  ___  __ _ _  _  _  __  __))";
$L "((_ \\(/'((_( ((\\( ((_)((_( (('((\\( ((\`1( ((_)((_( ";
$L "     ))                 _))";
$L " Parameter: $1";
