#!/system/bin/sh
L="log -p i -t cm"

###################################
# urandom tweak (seeder)

busybox sysctl -e -w kernel.random.read_wakeup_threshold=1376;
$L "Threshold written";

###################################
#  SD Read Speed Tweak  

busybox mount -o remount,noatime,noauto_da_alloc,nosuid,nodev,nodiratime,data=writeback,barrier=0,nobh /data

###################################
# Default I/O Scheduler Tweaks

#if [ -e /queue/iostats ]; then
#echo 0 > /queue/iostats;
#fi;  

#if [ -e /queue/rotational ]; then
#echo 0 > /queue/rotational; fi;
#if [ -e /queue/nr_requests ]; then
#echo 1024 > /queue/nr_requests; fi;


